name: Python package

on: [push]

jobs:
  run: 
    runs-on: ${{ matrix.operating-system }}
    strategy:
      max-parallel: 4
      matrix:
        operating-system: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7]
    steps:
    - uses: actions/checkout@v1
    - name: install dependencies and test
      env:
        PYVER: ${{ matrix.python-version }}
      run: |
        export PATH="$CONDA:$CONDA/bin:$PATH"
        echo "conda init bash ========================"
        conda init bash
        echo ". ~/.bashrc ============================"
        . ~/.bashrc
        echo "hash -r ================================"
        hash -r
        echo "conda update -q conda =================="
        conda config --set always_yes yes --set changeps1 no;
        conda update -q conda
        echo "conda create ==========================="
        conda create --name scisweeper --quiet --yes --channel conda-forge python=${PYVER} coverage pandas scandir h5io numpy pysqa tqdm pip
        echo "conda init bash ========================"
        conda init bash
        echo ". ~/.bashrc ============================"
        . ~/.bashrc
        echo "conda activate scisweeper =============="
        source activate scisweeper
        echo "pip install --pre ======================"
        pip install --pre .
        conda list
        echo "test ==================================="
        coverage run -m unittest discover tests
